### ISSUE TITLE
When archiving in xCode 13.3.1 error: Abort trap: 6 (in target 'SiFUtilities' from project 'Pods')

### ISSUE THREAD

**Issue by jarrillaga** [congncif/SiFUtilities#2]
Hi @congncif, I'm facing an issue when trying to archive a project which uses PagingDataController. I'm using xCode 13.3.1 and the error is:  error: Abort trap: 6 (in target 'SiFUtilities' from project 'Pods')

The problem is in this line: if keyboardFrame.size.height == 0, UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiom.pad {

UI_USER_INTERFACE_IDIOM() must be replaced by UIDevice.current.userInterfaceIdiom

I will change it locally but it would be excellent if you can fix it and release a new pod. 

Thanks in advance.

**Comment by congncif** [comment]
Hi @jarrillaga , Thanks for your report. I will check it soon.

**Comment by maxtran88** [comment]
![Screen Shot 2022-05-10 at 8 12 47 PM](https://user-images.githubusercontent.com/44662541/167636672-82f8b044-5004-4730-a699-2ebf397c1aaf.png)
![Screen Shot 2022-05-10 at 8 13 09 PM](https://user-images.githubusercontent.com/44662541/167636679-0f8b8731-de5d-4a53-a390-c95e6d264a91.png)

@congncif The same!

**Comment by congncif** [comment]
Fixed in version 4.27.3
Check it, my friends!
